<?php

namespace ContainerIPQjoc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DLhHqWZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DLhHqWZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cour' => ['privates', '.errored..service_locator.DLhHqWZ.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.DLhHqWZ": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cour' => 'App\\Entity\\Cours',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.DLhHqWZ'])) {
            return $container->privates['.service_locator.DLhHqWZ'];
        }

        return $container->privates['.service_locator.DLhHqWZ'] = $instance;
    }
}
