<?php

namespace ContainerIPQjoc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VOS60lhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vOS60lh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'resultatRepo' => ['privates', 'App\\Repository\\QuizResultatRepository', 'getQuizResultatRepositoryService', true],
            'service' => ['privates', 'App\\Service\\RecommendationService', 'getRecommendationServiceService', true],
        ], [
            'dispatcher' => '?',
            'resultatRepo' => 'App\\Repository\\QuizResultatRepository',
            'service' => 'App\\Service\\RecommendationService',
        ]);

        if (isset($container->privates['.service_locator.vOS60lh'])) {
            return $container->privates['.service_locator.vOS60lh'];
        }

        return $container->privates['.service_locator.vOS60lh'] = $instance;
    }
}
