<?php

namespace ContainerIPQjoc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__PlMuhSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..plMuhS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'quizRepo' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'dispatcher' => '?',
            'em' => '?',
            'quizRepo' => 'App\\Repository\\QuizRepository',
        ]);

        if (isset($container->privates['.service_locator..plMuhS'])) {
            return $container->privates['.service_locator..plMuhS'];
        }

        return $container->privates['.service_locator..plMuhS'] = $instance;
    }
}
