<?php

namespace ContainerIPQjoc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5_KxOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5.Kx__o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaire' => ['privates', '.errored..service_locator.5.Kx__o.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.5.Kx__o": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.5.Kx__o'])) {
            return $container->privates['.service_locator.5.Kx__o'];
        }

        return $container->privates['.service_locator.5.Kx__o'] = $instance;
    }
}
