<?php

namespace ContainerIPQjoc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatbotServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ChatbotService' shared autowired service.
     *
     * @return \App\Service\ChatbotService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ChatbotService.php';

        return $container->privates['App\\Service\\ChatbotService'] = new \App\Service\ChatbotService(($container->privates['App\\Repository\\CoursRepository'] ?? $container->load('getCoursRepositoryService')), ($container->privates['App\\Repository\\ChapitreRepository'] ?? $container->load('getChapitreRepositoryService')), ($container->privates['App\\Repository\\QuizRepository'] ?? $container->load('getQuizRepositoryService')));
    }
}
