<?php

namespace ContainerIPQjoc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\NotificationEventSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\NotificationEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'NotificationEventSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NotificationService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\NotificationEventSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\NotificationEventSubscriber'];
        }

        $instance = new \App\EventSubscriber\NotificationEventSubscriber(new \App\Service\NotificationService($a, ($container->privates['App\\Repository\\CoursRepository'] ?? $container->load('getCoursRepositoryService'))));

        if (isset($container->privates['App\\EventSubscriber\\NotificationEventSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\NotificationEventSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\NotificationEventSubscriber'] = $instance;
    }
}
