vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        expert_images:
            uri_prefix: /uploads/experts
            upload_destination: '%kernel.project_dir%/public/uploads/experts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer