<?php

namespace ContainerHD4xidr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FrSv9vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fr_sv9v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\NotificationRepository',
        ]);

        if (isset($container->privates['.service_locator.fr_sv9v'])) {
            return $container->privates['.service_locator.fr_sv9v'];
        }

        return $container->privates['.service_locator.fr_sv9v'] = $instance;
    }
}
