<?php

namespace ContainerHD4xidr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3bzAsN0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3bzAsN0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3bzAsN0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'coursRepo' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'recommendationService' => ['privates', 'App\\Service\\RecommendationService', 'getRecommendationServiceService', true],
            'resultatRepo' => ['privates', 'App\\Repository\\QuizResultatRepository', 'getQuizResultatRepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'coursRepo' => 'App\\Repository\\CoursRepository',
            'recommendationService' => 'App\\Service\\RecommendationService',
            'resultatRepo' => 'App\\Repository\\QuizResultatRepository',
        ]);
    }
}
