<?php

namespace ContainerHD4xidr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\EasyAdmin\QuizCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\EasyAdmin\QuizCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'easycorp'.\DIRECTORY_SEPARATOR.'easyadmin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Contracts'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'easycorp'.\DIRECTORY_SEPARATOR.'easyadmin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'EasyAdmin'.\DIRECTORY_SEPARATOR.'QuizCrudController.php';

        $instance = new \App\Controller\Admin\EasyAdmin\QuizCrudController();

        if (isset($container->services['App\\Controller\\Admin\\EasyAdmin\\QuizCrudController'])) {
            return $container->services['App\\Controller\\Admin\\EasyAdmin\\QuizCrudController'];
        }

        $container->services['App\\Controller\\Admin\\EasyAdmin\\QuizCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.J2.HZpr'] ?? $container->load('get_ServiceLocator_J2_HZprService'))->withContext('App\\Controller\\Admin\\EasyAdmin\\QuizCrudController', $container));

        return $instance;
    }
}
