<?php

namespace ContainerHD4xidr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RecommendationService' shared autowired service.
     *
     * @return \App\Service\RecommendationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecommendationService.php';

        return $container->privates['App\\Service\\RecommendationService'] = new \App\Service\RecommendationService(($container->privates['App\\Repository\\CoursRepository'] ?? $container->load('getCoursRepositoryService')), ($container->privates['App\\Repository\\QuizResultatRepository'] ?? $container->load('getQuizResultatRepositoryService')));
    }
}
