<?php

namespace ContainerDlQSXMA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3AenG_LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3AenG.L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'quiz' => ['privates', '.errored..service_locator.3AenG.L.App\\Entity\\Quiz', NULL, 'Cannot autowire service ".service_locator.3AenG.L": it needs an instance of "App\\Entity\\Quiz" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'quiz' => 'App\\Entity\\Quiz',
        ]);

        if (isset($container->privates['.service_locator.3AenG.L'])) {
            return $container->privates['.service_locator.3AenG.L'];
        }

        return $container->privates['.service_locator.3AenG.L'] = $instance;
    }
}
