<?php

namespace ContainerDlQSXMA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0LY868_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0LY868.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0LY868.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentRepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'coursRepo' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'quizRepo' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'commentRepo' => 'App\\Repository\\CommentaireRepository',
            'coursRepo' => 'App\\Repository\\CoursRepository',
            'quizRepo' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
