<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPQjoc9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPQjoc9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPQjoc9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIPQjoc9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIPQjoc9\App_KernelDevDebugContainer([
    'container.build_hash' => 'IPQjoc9',
    'container.build_id' => 'e78708d9',
    'container.build_time' => 1776202671,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPQjoc9');
