<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDlQSXMA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDlQSXMA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDlQSXMA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDlQSXMA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDlQSXMA\App_KernelDevDebugContainer([
    'container.build_hash' => 'DlQSXMA',
    'container.build_id' => 'a166cc49',
    'container.build_time' => 1775407596,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDlQSXMA');
